using System.Net;
using System.Net.Mail;
using K8SMonitor.Configuration;

namespace K8SMonitor.Services;

/// <summary>
/// Sends notification emails (e.g. when a pull request is created).
/// Uses System.Net.Mail so no extra NuGet package is required.
/// </summary>
public class EmailService
{
    private readonly K8SMonitorConfig _config;

    public EmailService(K8SMonitorConfig config)
    {
        _config = config ?? throw new ArgumentNullException(nameof(config));
    }

    /// <summary>
    /// Sends an email notifying configured recipients that a pull request was created.
    /// Silently no-ops when EmailEnabled is false or no recipients are configured.
    /// </summary>
    public async Task SendPullRequestCreatedAsync(
        int prNumber,
        string prUrl,
        string prTitle,
        string podName,
        string @namespace,
        IEnumerable<string> filesModified,
        string aiSummary)
    {
        if (!_config.EmailEnabled)
            return;

        if (_config.PrNotifyEmails.Length == 0)
        {
            Console.WriteLine("  ⚠️  Email enabled but PR_NOTIFY_EMAILS is empty - skipping notification");
            return;
        }

        try
        {
            using var message = new MailMessage
            {
                From = new MailAddress(_config.EmailFrom, _config.EmailFromName),
                Subject = $"[K8SMonitor] PR #{prNumber} created: {prTitle}",
                IsBodyHtml = true,
                Body = BuildHtmlBody(prNumber, prUrl, prTitle, podName, @namespace, filesModified, aiSummary)
            };

            foreach (var recipient in _config.PrNotifyEmails)
            {
                message.To.Add(recipient);
            }

            using var smtp = new SmtpClient(_config.SmtpHost, _config.SmtpPort)
            {
                EnableSsl = _config.SmtpUseSsl,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
            };

            if (!string.IsNullOrWhiteSpace(_config.SmtpUser))
            {
                smtp.Credentials = new NetworkCredential(_config.SmtpUser, _config.SmtpPassword);
            }

            await smtp.SendMailAsync(message);

            Console.WriteLine($"  ✉️  Notification email sent to: {string.Join(", ", _config.PrNotifyEmails)}");
        }
        catch (Exception ex)
        {
            // Don't blow up the whole pipeline if the mail server is unreachable.
            Console.WriteLine($"  ⚠️  Failed to send notification email: {ex.Message}");
        }
    }

    private static string BuildHtmlBody(
        int prNumber,
        string prUrl,
        string prTitle,
        string podName,
        string @namespace,
        IEnumerable<string> filesModified,
        string aiSummary)
    {
        var files = string.Join("", filesModified.Select(f => $"<li><code>{WebUtility.HtmlEncode(f)}</code></li>"));
        var summaryHtml = WebUtility.HtmlEncode(aiSummary ?? string.Empty)
            .Replace("\n", "<br/>");

        return $@"
<html>
  <body style=""font-family: Segoe UI, Arial, sans-serif; color:#222;"">
    <h2 style=""color:#0366d6; margin-bottom:4px;"">🔧 Pull Request #{prNumber} created</h2>
    <p style=""margin-top:0; color:#555;"">An automated fix was generated by <b>K8SMonitor</b>.</p>

    <table cellpadding=""6"" style=""border-collapse:collapse; margin:12px 0;"">
      <tr><td><b>Title</b></td><td>{WebUtility.HtmlEncode(prTitle)}</td></tr>
      <tr><td><b>Pod</b></td><td><code>{WebUtility.HtmlEncode(podName)}</code></td></tr>
      <tr><td><b>Namespace</b></td><td><code>{WebUtility.HtmlEncode(@namespace)}</code></td></tr>
      <tr><td><b>PR URL</b></td><td><a href=""{prUrl}"">{prUrl}</a></td></tr>
    </table>

    <h3>Files modified</h3>
    <ul>{files}</ul>

    <h3>AI summary</h3>
    <div style=""padding:10px; background:#f6f8fa; border-left:3px solid #0366d6;"">
      {summaryHtml}
    </div>

    <p style=""color:#888; font-size:12px; margin-top:24px;"">
      This email was sent automatically by K8SMonitor. Please review and merge the PR if appropriate.
    </p>
  </body>
</html>";
    }
}
