using Octokit;

namespace K8SMonitor.Services;

public class GitHubPRService
{
    private readonly GitHubClient _client;
    private readonly string _owner;
    private readonly string _repo;
    private readonly string _baseBranch;

    public GitHubPRService(string token, string owner, string repo, string baseBranch = "main")
    {
        _client = new GitHubClient(new ProductHeaderValue("K8SMonitor"))
        {
            Credentials = new Credentials(token)
        };
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
        _repo = repo ?? throw new ArgumentNullException(nameof(repo));
        _baseBranch = baseBranch;
    }

    public async Task<int> CreatePullRequestAsync(string branchName, string title, string description, string fileChanges)
    {
        try
        {
            // Get the default branch SHA
            var mainRef = await _client.Git.Reference.Get(_owner, _repo, $"heads/{_baseBranch}");
            var mainSha = mainRef.Object.Sha;

            // Create new branch
            var newRef = new NewReference($"refs/heads/{branchName}", mainSha);
            await _client.Git.Reference.Create(_owner, _repo, newRef);

            Console.WriteLine($"✓ Created branch: {branchName}");

            // Create or update file with changes
            var existingFile = await GetFileIfExistsAsync(fileChanges);
            
            if (existingFile != null)
            {
                var updateRequest = new UpdateFileRequest(
                    message: $"Auto-fix: {title}",
                    content: fileChanges,
                    sha: existingFile.Sha,
                    branch: branchName
                );
                await _client.Repository.Content.UpdateFile(_owner, _repo, existingFile.Path, updateRequest);
                Console.WriteLine($"✓ Updated file: {fileChanges}");
            }
            else
            {
                var createRequest = new CreateFileRequest(
                    message: $"Auto-fix: {title}",
                    content: fileChanges,
                    branch: branchName
                );
                await _client.Repository.Content.CreateFile(_owner, _repo, fileChanges, createRequest);
                Console.WriteLine($"✓ Created file: {fileChanges}");
            }

            // Create pull request
            var prRequest = new NewPullRequest(title, branchName, _baseBranch)
            {
                Body = $"{description}\n\n**Automated by K8SMonitor**\n\nThis PR was automatically generated by analyzing Kubernetes pod logs and using AI to suggest fixes."
            };

            var pr = await _client.PullRequest.Create(_owner, _repo, prRequest);
            Console.WriteLine($"✓ Created Pull Request #{pr.Number}: {pr.HtmlUrl}");

            return pr.Number;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Failed to create pull request: {ex.Message}", ex);
        }
    }

    private async Task<RepositoryContent?> GetFileIfExistsAsync(string filePath)
    {
        try
        {
            var content = await _client.Repository.Content.GetAllContentsByRef(_owner, _repo, filePath, _baseBranch);
            return content.FirstOrDefault();
        }
        catch
        {
            return null;
        }
    }

    public async Task<List<string>> GetRecentErrorBranchesAsync(int limit = 10)
    {
        // Note: In Octokit v5, branch listing requires different API
        // For now, returning empty list - this method is optional for the core workflow
        await Task.CompletedTask;
        return new List<string>();
    }
}
