using Octokit;
using System.Text;

namespace K8SMonitor.Services;

public class GitHubPRService
{
    private readonly GitHubClient _client;
    private readonly string _owner;
    private readonly string _repo;
    private readonly string _baseBranch;

    public GitHubPRService(string token, string owner, string repo, string baseBranch = "main")
    {
        _client = new GitHubClient(new ProductHeaderValue("K8SMonitor"))
        {
            Credentials = new Credentials(token)
        };
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
        _repo = repo ?? throw new ArgumentNullException(nameof(repo));
        _baseBranch = baseBranch;
    }

    /// <summary>
    /// Creates a single PR with fixes for multiple files from a pod error.
    /// All fixes are applied to the same branch and included in one PR.
    /// </summary>
    public async Task<int> CreatePullRequestWithMultipleCodeFixesAsync(string branchName, string title, string description, List<CodeFix> codeFixes)
    {
        try
        {
            if (!codeFixes.Any())
                throw new InvalidOperationException("No code fixes provided");

            // Get the default branch SHA
            var mainRef = await _client.Git.Reference.Get(_owner, _repo, $"heads/{_baseBranch}");
            var mainSha = mainRef.Object.Sha;

            // Create new branch
            var newRef = new NewReference($"refs/heads/{branchName}", mainSha);
            await _client.Git.Reference.Create(_owner, _repo, newRef);

            Console.WriteLine($"✓ Created branch: {branchName}");

            // Apply all fixes to their respective files
            var appliedFixes = new List<CodeFix>();
            foreach (var codeFix in codeFixes)
            {
                // Fetch existing file from GitHub
                var existingFile = await GetFileContentAsync(codeFix.FilePath);
                
                if (existingFile == null)
                {
                    Console.WriteLine($"  ⚠️  Could not find file: {codeFix.FilePath} - skipping this fix");
                    continue;
                }

                // Apply the fix to the code
                var fixedContent = existingFile.Content.Replace(codeFix.OriginalCode, codeFix.FixedCode);
                
                if (fixedContent == existingFile.Content)
                {
                    Console.WriteLine($"  ⚠️  Code fix could not be applied to {codeFix.FilePath} - original code not found");
                    continue;
                }

                // Update file with fixed code
                var updateRequest = new UpdateFileRequest(
                    message: $"Auto-fix: {title}",
                    content: fixedContent,
                    sha: existingFile.Sha,
                    branch: branchName
                );
                
                await _client.Repository.Content.UpdateFile(_owner, _repo, codeFix.FilePath, updateRequest);
                Console.WriteLine($"  ✓ Fixed file: {codeFix.FilePath}");
                appliedFixes.Add(codeFix);
            }

            if (!appliedFixes.Any())
            {
                throw new InvalidOperationException("No fixes could be successfully applied to any files");
            }

            // Build PR body with all fixes
            var changesSection = new StringBuilder();
            changesSection.AppendLine("## 🔧 Changes Made\n");
            
            foreach (var fix in appliedFixes)
            {
                changesSection.AppendLine($"### 📄 {fix.FilePath}");
                changesSection.AppendLine($"**Why:** {fix.Explanation}\n");
                changesSection.AppendLine("#### Original Code");
                changesSection.AppendLine($"```csharp\n{fix.OriginalCode}\n```\n");
                changesSection.AppendLine("#### Fixed Code");
                changesSection.AppendLine($"```csharp\n{fix.FixedCode}\n```\n");
                changesSection.AppendLine("---\n");
            }

            var prBody = $@"{description}

{changesSection}

**Files Modified:** {appliedFixes.Count}
- {string.Join("\n- ", appliedFixes.Select(f => f.FilePath))}

---

**Automated by K8SMonitor** - This PR was automatically generated by analyzing Kubernetes pod logs and using AI to suggest and apply fixes to multiple files.";

            var prRequest = new NewPullRequest(title, branchName, _baseBranch)
            {
                Body = prBody
            };

            var pr = await _client.PullRequest.Create(_owner, _repo, prRequest);
            Console.WriteLine($"✓ Created Pull Request #{pr.Number} with {appliedFixes.Count} file fix(es): {pr.HtmlUrl}");

            return pr.Number;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Failed to create pull request with multiple code fixes: {ex.Message}", ex);
        }
    }

    public async Task<int> CreatePullRequestWithCodeFixAsync(string branchName, string title, string description, CodeFix codeFix)
    {
        try
        {
            // Get the default branch SHA
            var mainRef = await _client.Git.Reference.Get(_owner, _repo, $"heads/{_baseBranch}");
            var mainSha = mainRef.Object.Sha;

            // Create new branch
            var newRef = new NewReference($"refs/heads/{branchName}", mainSha);
            await _client.Git.Reference.Create(_owner, _repo, newRef);

            Console.WriteLine($"✓ Created branch: {branchName}");

            // Fetch existing file from GitHub
            var existingFile = await GetFileContentAsync(codeFix.FilePath);
            
            if (existingFile == null)
            {
                throw new InvalidOperationException($"Could not find file: {codeFix.FilePath}");
            }

            // Apply the fix to the code
            var fixedContent = existingFile.Content.Replace(codeFix.OriginalCode, codeFix.FixedCode);
            
            if (fixedContent == existingFile.Content)
            {
                throw new InvalidOperationException("Code fix could not be applied - original code not found in file");
            }

            // Update file with fixed code
            var updateRequest = new UpdateFileRequest(
                message: $"Auto-fix: {title}\n\n{codeFix.Explanation}",
                content: fixedContent,
                sha: existingFile.Sha,
                branch: branchName
            );
            
            await _client.Repository.Content.UpdateFile(_owner, _repo, codeFix.FilePath, updateRequest);
            Console.WriteLine($"✓ Fixed file: {codeFix.FilePath}");

            // Create pull request
            var prBody = $@"{description}

## 🔧 Changes Made

**File:** `{codeFix.FilePath}`

**Why:** {codeFix.Explanation}

### Original Code
```csharp
{codeFix.OriginalCode}
```

### Fixed Code
```csharp
{codeFix.FixedCode}
```

---

**Automated by K8SMonitor** - This PR was automatically generated by analyzing Kubernetes pod logs and using AI to suggest and apply fixes.";

            var prRequest = new NewPullRequest(title, branchName, _baseBranch)
            {
                Body = prBody
            };

            var pr = await _client.PullRequest.Create(_owner, _repo, prRequest);
            Console.WriteLine($"✓ Created Pull Request #{pr.Number}: {pr.HtmlUrl}");

            return pr.Number;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Failed to create pull request with code fix: {ex.Message}", ex);
        }
    }

    public class FileContent
    {
        public string Content { get; set; } = string.Empty;
        public string Sha { get; set; } = string.Empty;
        /// <summary>Resolved full path in the repository (e.g. src/Worker/Program.cs)</summary>
        public string Path { get; set; } = string.Empty;
    }

    public async Task<FileContent?> GetFileContentAsync(string filePath)
    {
        try
        {
            var content = await _client.Repository.Content.GetAllContentsByRef(_owner, _repo, filePath, _baseBranch);
            var file = content.FirstOrDefault();

            if (file == null)
                return null;

            string decodedContent;
            try
            {
                // GitHub wraps base64 with newlines every 60 chars — strip all whitespace before decoding
                var cleanBase64 = file.Content
                    .Replace("\n", "")
                    .Replace("\r", "")
                    .Replace(" ", "");
                decodedContent = System.Text.Encoding.UTF8.GetString(
                    Convert.FromBase64String(cleanBase64)
                );
            }
            catch (FormatException)
            {
                // Octokit may have already decoded the content in some versions/configurations
                decodedContent = file.Content ?? string.Empty;
            }

            return new FileContent
            {
                Content = decodedContent,
                Sha = file.Sha,
                Path = filePath
            };
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ⚠️  GetFileContentAsync failed for '{filePath}': {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Searches the entire repo tree for a file matching the given filename (e.g. "Program.cs").
    /// Returns the first full path found (e.g. "src/Worker/Program.cs"), or null if not found.
    /// </summary>
    public async Task<string?> SearchFileByNameAsync(string fileName)
    {
        try
        {
            var tree = await _client.Git.Tree.GetRecursive(_owner, _repo, _baseBranch);
            var match = tree.Tree.FirstOrDefault(item =>
                item.Type == TreeType.Blob &&
                string.Equals(System.IO.Path.GetFileName(item.Path), fileName, StringComparison.OrdinalIgnoreCase));
            return match?.Path;
        }
        catch
        {
            return null;
        }
    }

    public async Task<int> CreatePullRequestAsync(string branchName, string title, string description, string fileName, string fileContent)
    {
        try
        {
            // Get the default branch SHA
            var mainRef = await _client.Git.Reference.Get(_owner, _repo, $"heads/{_baseBranch}");
            var mainSha = mainRef.Object.Sha;

            // Create new branch
            var newRef = new NewReference($"refs/heads/{branchName}", mainSha);
            await _client.Git.Reference.Create(_owner, _repo, newRef);

            Console.WriteLine($"✓ Created branch: {branchName}");

            // Create or update markdown file with solutions
            var existingFile = await GetFileIfExistsAsync(fileName);
            
            if (existingFile != null)
            {
                var updateRequest = new UpdateFileRequest(
                    message: $"Auto-fix: {title}",
                    content: Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(fileContent)),
                    sha: existingFile.Sha,
                    branch: branchName
                );
                await _client.Repository.Content.UpdateFile(_owner, _repo, existingFile.Path, updateRequest);
                Console.WriteLine($"✓ Updated file: {fileName}");
            }
            else
            {
                var createRequest = new CreateFileRequest(
                    message: $"Auto-fix: {title}",
                    content: Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(fileContent)),
                    branch: branchName
                );
                await _client.Repository.Content.CreateFile(_owner, _repo, fileName, createRequest);
                Console.WriteLine($"✓ Created file: {fileName}");
            }

            // Create pull request
            var prRequest = new NewPullRequest(title, branchName, _baseBranch)
            {
                Body = $"{description}\n\n**Automated by K8SMonitor**\n\nThis PR was automatically generated by analyzing Kubernetes pod logs and using AI to suggest fixes.\n\n**Fix Details:** See the `{fileName}` file in this PR for complete analysis and solutions."
            };

            var pr = await _client.PullRequest.Create(_owner, _repo, prRequest);
            Console.WriteLine($"✓ Created Pull Request #{pr.Number}: {pr.HtmlUrl}");

            return pr.Number;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Failed to create pull request: {ex.Message}", ex);
        }
    }

    private async Task<RepositoryContent?> GetFileIfExistsAsync(string filePath)
    {
        try
        {
            var content = await _client.Repository.Content.GetAllContentsByRef(_owner, _repo, filePath, _baseBranch);
            return content.FirstOrDefault();
        }
        catch
        {
            return null;
        }
    }

    public async Task<List<string>> GetRecentErrorBranchesAsync(int limit = 10)
    {
        // Note: In Octokit v5, branch listing requires different API
        // For now, returning empty list - this method is optional for the core workflow
        await Task.CompletedTask;
        return new List<string>();
    }
}
